version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: web_backend_lab
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=web_backend_lab

volumes:
  mysql_data:
